import './js/loader.js';
import './js/dark-mode.js';
import './js/rendering-movies-by-id.js';
import './js/modal-movie.js';
import './js/team-modal.js';
import './js/auth-menu.js';
import './js/firebase-app.js';
import './js/sign-up.js';
import './js/login.js';
